"""Third migration

Revision ID: 6739b1111d8c
Revises: 82f62c416083
Create Date: 2022-11-21 10:42:26.269399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6739b1111d8c'
down_revision = '82f62c416083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_family_member_name'), ['name'])

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_household_address'), ['address'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=32), nullable=True))
        batch_op.drop_constraint('uq_users_session_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_user_id'), ['user_id'])
        batch_op.drop_column('session_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_key', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('uq_users_session_key', ['session_key'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_household_address'), type_='unique')

    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_family_member_name'), type_='unique')

    # ### end Alembic commands ###
