"""Initial migration

Revision ID: 8004db54f067
Revises: 
Create Date: 2022-11-21 01:24:19.426226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8004db54f067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_key', sa.String(length=32), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=345),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=345),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('session_key')

    # ### end Alembic commands ###
